### ISSUE TITLE
INSTALL.mdの環境、packageの記載について

### ISSUE THREAD

**Issue by monagai** [NCCJapan/cisCall5_doc#3]
すみません，新規issueにしました．To: @joemphilips 

現時点のmasterのINSTALL.mdの上半分だけで，下記指摘あり．
直接直してもいいならそうしますが，それはそれであぶない気も...

+ Required Environment:
  - "installation of cisCall"
    - タイトルと説明が合わない．ここは環境設定ですよね．
  - R : 
    - Cton5とCton7あわせると私は3.2.2でしか確認取っていません．(3.1.1で動くのかわからない)
    - .configureで--enable-R-shlib --with-libpngオプションつけてmake要
    - cluster", "coin", "RPMM", "VGAM", "exactRankTests" 要．(私が環境作成で指定しているのはこれだけ)
  - Python: 
    -  .configureで --enable-shared --enable-loadable-sqlite-extensions オプションつけてmake要
       ※つまり sqlite も必要とわかる．書いておかないと"記載不十分"の印象を与えないか，やや気になる．
    - six，scipy，numpy，rpy2要 (他は指定不要という認識)
    - 私が動作確認したのは3.4.3です
  - Perl: 
    - 版数は? V5以上とかでも良いのかもしれませんが．
    - Math::CDF必須

+ Required Packages
  - CutAdapt, Cython, Varscan，Annovar不要
  - BWAとSamtoolsは，cisFusion5，cisMutonに含まれているのでインストール不要．(ここに書いておく必要はあるが)
  - cisXXX別にしない方がいいです．(だったら，RとかもPyhon3自体も分けないと変)

+ Java: 版数は?

+ ちなみにCentOS6.8-minimalから今入れているのは下記。どこまで書くか(最後のlibpng～pango-develはとcisCton7が動かなかったですが。)
  git wget gcc gcc-c++ gcc-gfortran readline-devel zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel tk-devel java-1.8.0-openjdk libpng-devel cairo-devel pango pango-devel
perl-CPAN perl-YAML

※私の感覚だと，readmeはまだかなり先は長いという感じです．

**Comment by joemphilips** [comment]
ありがとうございます。修正点を#4 にあげました

**Comment by monagai** [comment]
R:
- 以下は不要と思うけど．．．(使っているかもしれないがインストールはしなくても済んでいる．)
  - MASS
  - KernSmooth
  - grDevices
  - parallel
- clusterは要るように思う．
- Javaの版は何でもOK? 動作確認が取れている以上の版を書く?
- bigWigtobedGraphはRでありません．(これ，私，まじめに素性がわかりません．バイナリ単体です)
- 細かいですが，"since python uses rpy2 for calling R function, python and R needs to be compiled from source with following option"
  "since python uses rpy2 for calling R function"は無くて良いと思います．
  "python ... --enable-shared --enable-loadable-sqlite-extensions"のような書き方だと，python自体の実行オプションぽく見えてしまう．
  "pytthon: ".configure --enable-shared --enable-loadable-sqlite-extensions" とか,
  "pytthon .congire オプション: ".configure --enable-shared --enable-loadable-sqlite-extensions" 

Optional Software
- 使い方を説明する気がないのなら外すべき．入れるということは，書くということ．

**Comment by monagai** [comment]
INSTALL.md のbigWigtobedGraphはRとかpythonと同列は変で、packages which are included in cisCall.では。
あと、Muton とか Fusion とかではなく、全部きちんとcisMutonとかcisFusionとか揃えたほうがいいです(英文法違反にならない範囲で大文字、小文字も。Ciscto7とかまだあった気がする)
すみません、変更部分じゃないところはソースにコメント入れられないんですよね?

**Comment by monagai** [comment]
事後ですみません、
example実行のところで
「cisCton: execute $ ./example.cton.sh at /home/cisusr/run_cisCton. Note that you must run cisMuton before cisCton.」と入っているけれど、cisCtonのサンプルってmutonのbam作りまで含めます?? 
私はサンプル作りはbam(chr単位に分割したもの)から進めていたんですが、それならmutonのfastqにまで戻らないといけません。
mutonの結果のサンプルbamからexample.cton.shをスタートするなら、"Note that you must run cisMuton before cisCton."はINSTALL.mdで言う必要はなく、cton.mdで説明すればいいと思います。

**Comment by joemphilips** [comment]
すみません。確かにMutonのテストサンプルとCtonのそれは別なので、ここでいう必要はありませんでした。

`cton.md`でもそうですが、`user_defined_data.md` に書いておけば問題ないかと思います。

消去してmasterにpushします。

**Comment by joemphilips** [comment]
pushしました

**Comment by monagai** [comment]
早速ありがとうございます

**Comment by monagai** [comment]
ctonのサンプル作って、mutonも以前決めた名前(PANEL_FOR_TESTとか)にrenameしていてハタと気づいたのですが、cisCall5のGUIを使ってパラメタをsetさせる仕様ではなく、お仕着せのparamを使わせるのであればparam下のfile名をrenameしないといけません。すっごく忘れそうなのであげておきます

**Comment by monagai** [comment]
paramの件ですが、他の条件(シーケンサが違うとか)のパラメタ設定を説明されます?(いや、ほんとはしないといけないんだけど)...
そして、それがCton7とどうからむのか私はわかっていないのですが。。

**Comment by joemphilips** [comment]
> ctonのサンプル作って、mutonも以前決めた名前(PANEL_FOR_TESTとか)にrenameしていてハタと気づいたのですが、cisCall5のGUIを使ってパラメタをsetさせる仕様ではなく、お仕着せのparamを使わせるのであればparam下のfile名をrenameしないといけません。すっごく忘れそうなのであげておきます

公開イメージの作成中にイメージ内でパラメータセット用のコマンドを走らせればOKなのでは？
TODOとして挙げるならば #1 に追記するのをお勧めします。

> paramの件ですが、他の条件(シーケンサが違うとか)のパラメタ設定を説明されます?(いや、ほんとはしないといけないんだけど)...

さすがに FFPE/Frozen くらいは説明をする必要があると思います。 `doc/options.md` をアップデートする段階で書きましょう。(パネル名・増幅方法に関してはどう書けばよいか私にはわからないです。)
`doc/user_defined_data.md` で`before calling your sample, set proper parameter, see next section for details` と言っておいて詳しい説明を`doc/options.md`に書くというので良いのではないでしょうか。

> そして、それがCton7とどうからむのか私はわかっていないのですが。。

私もわかりません。`--param`を与えなくても動作したと思うので、必要ないのではないかと思っています。

**Comment by monagai** [comment]
本当は，cisCall5のパラメタ選択肢は下記の通りあります．
(これは少し前の手元のメモなので，もっとあるかもしれない．)

[cisCallパラメタセット選択肢] 
--------------------------------begin---------------------------------
 1: Ion      PGM/Proton,  Frozen
 2: Ion      PGM/Proton,  Methanol
 3: Ion      PGM/Proton,  FFPE
 4: Illumina HiSeq/MiSeq, SureSelect-Frozen
 5: Illumina HiSeq/MiSeq, SureSelect-FFPE
 6: Illumina HiSeq/MiSeq, HaloPlex-Frozen
 7: Illumina HiSeq/MiSeq, Single-Cell
---------------------------------end----------------------------------

もう1個別のメモ
--------------------------------begin---------------------------------
  シーケンサ               増幅        FF/Fr    アダプタ除去  DUP除去
  イルミナ(Miseq/Hiseq)    Haloplex    FF       ○            ×(※)
  イルミナ(Miseq/Hiseq)    Haloplex    Fr       ○            ×(※)
  イルミナ(Miseq/Hiseq)    SureSelect  FF       ○            ○
  イルミナ(Miseq/Hiseq)    SureSelect  Fr       ○            ×
  Ion(PGM/Proton)          AmpliSeq    FF       ×            ×(※)
  Ion(PGM/Proton)          AmpliSeq    Fr       ×            ×(※)
  ※+ ver5.0.2以前: 凍結とFFPEが混在している場合は、Tumor側に合わせる
    + ver5.0.3d以降: TumorとNormalそれぞれ指定出来る．上記の表に従う
---------------------------------end----------------------------------

加藤先生が，cisCall論文でどこまでできると言いたいかに依るかな．
(cisCton7は，4,5しか調整済ではないのですかな???)

4，5だけでいいですよねと一応加藤先生に確認します

**Comment by joemphilips** [comment]
> `doc/options.md` をアップデートする段階で書きましょう。

と述べましたが、ユーザーのfastqを使用する段階でparamをセットしていただく必要が生じる可能性が高いため、設定が必要な `param` のGUIでの設定方法に関しては `doc/user_defined_data.md` に書くことにしましょう。

**Comment by joemphilips** [comment]
Issueのタイトルの内容の修正は完了したので、closeします。
